
spring:
  cloud:
    stream:
      bindings:
        # 用户通道 userInput为bindings包下
        userInput:
          destination: crmDemo
          binder: defaultRabbit
          group: hehe
        testInput:
          destination: crmTest
          binder: defaultRabbit
          group: haha
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                username: test
                password: 123456
                host: 192.168.10.22
                port: 5672
                virtual-host: /
          default-binder: defaultRabbit
      rabbit:
        bindings:
          userInput:
            consumer:
              bindingRoutingKey: demo
